#!/usr/bin/env bash

cd ~/win/projects/notation-fun/notation
BRANCH=`git rev-parse --abbrev-ref HEAD`

if [[ "$BRANCH" =~ ^release-wasm$ ]] ; then
    cd `dirname $0`
    cd ../static/notation
    rm -rf assets
    mkdir assets

    cp -v ~/win/projects/notation-fun/notation/public/notation/* .
    cp -vr ~/win/projects/notation-fun/notation/apps/notation_viewer/assets/fonts assets/
    cp -vr ~/win/projects/notation-fun/notation/apps/notation_viewer/assets/png assets/
    cp -vr ~/win/projects/notation-fun/notation/apps/notation_viewer/assets/songs assets/
else
    echo "Wrong Branch: expected: release-wasm actual: $BRANCH"
fi


